"""mushroom_img updated Mushroom

Revision ID: 1855e9196731
Revises: a02e379abf56
Create Date: 2022-05-19 21:18:59.943137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1855e9196731'
down_revision = 'a02e379abf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mushroom', sa.Column('img_scr', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mushroom', 'img_scr')
    # ### end Alembic commands ###
