"""added created_on to Temperature

Revision ID: 563ff01f98af
Revises: ec1b3a792535
Create Date: 2022-05-19 16:40:44.655191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563ff01f98af'
down_revision = 'ec1b3a792535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temperature', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temperature', 'created_on')
    # ### end Alembic commands ###
