"""mushroom_img updated Mushroom

Revision ID: a02e379abf56
Revises: 251369eda79f
Create Date: 2022-05-19 21:18:32.793127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a02e379abf56'
down_revision = '251369eda79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mushroom', 'img_scr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mushroom', sa.Column('img_scr', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
