"""added Mushroom table

Revision ID: 860ef4decd54
Revises: 
Create Date: 2022-05-19 15:50:16.950395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860ef4decd54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mushroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spawn_temp', sa.Integer(), nullable=True),
    sa.Column('fruit_temp', sa.Integer(), nullable=True),
    sa.Column('spawn_fae', sa.Integer(), nullable=True),
    sa.Column('fruit_fae', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mushroom_id'), 'mushroom', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mushroom_id'), table_name='mushroom')
    op.drop_table('mushroom')
    # ### end Alembic commands ###
