"""added mushroom_id to Note.

Revision ID: bd70f92dcd56
Revises: ae28be18edd6
Create Date: 2022-06-13 14:17:12.174332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd70f92dcd56'
down_revision = 'ae28be18edd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('mushroom_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'note', 'mushroom', ['mushroom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'mushroom_id')
    # ### end Alembic commands ###
