"""mushroom_img updated Mushroom

Revision ID: c6efbcc24001
Revises: 1855e9196731
Create Date: 2022-05-19 21:20:01.435303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6efbcc24001'
down_revision = '1855e9196731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mushroom', sa.Column('mushroom_img', sa.String(length=200), nullable=True))
    op.drop_column('mushroom', 'img_scr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mushroom', sa.Column('img_scr', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('mushroom', 'mushroom_img')
    # ### end Alembic commands ###
